name: see_v
description: A new Flutter project

environment:
  sdk: '^3.1.0'

dependencies:
  flutter_lints: ^1.0.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  firebase: ^9.0.3
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  animated_text_kit: ^4.2.2
  image_picker: ^0.8.4+1
  firebase_storage: ^11.5.6
  hover: ^0.4.0
  url_launcher_windows: ^3.1.1
  webview_flutter: ^4.4.2


flutter:
  assets:
    - assets/logofinal.png
    - assets/cv example1.webp
    - assets/cvexample2.webp
    - assets/UPDATE.png
    - assets/updateimage.png
    - assets/homeimage.png
    - assets/blogs.jpeg
    - assets/template1.png
    - assets/template2.jpg
    - assets/template3.jpg